require 'rubygems'
require 'rake'

# Assume a typical dev checkout to fetch the current merb-core version
require 'merb-core/version'

begin

  require 'jeweler'

  Jeweler::Tasks.new do |gemspec|

    gemspec.version     = '0.0.0'

    gemspec.name        = "very-thin-test-slice"
    gemspec.description = "The description of your slice"
    gemspec.summary     = "The summary of your slice"

    gemspec.authors     = [ "Your name" ]
    gemspec.email       = "your@email.com"
    gemspec.homepage    = "http://example.org/"

    # Runtime dependencies
    gemspec.add_dependency 'merb-slices', "#{Merb::VERSION}"

  end

  Jeweler::GemcutterTasks.new

rescue LoadError
  puts "Jeweler (or a dependency) not available. Install it with: gem install jeweler"
end
