require 'rubygems'
require 'rake'

# Assume a typical dev checkout to fetch the current merb-core version
require File.expand_path('../../merb-core/lib/merb-core/version', __FILE__)

# Load this library's version information
require File.expand_path('../lib/merb-slices/version', __FILE__)

begin

  gem 'jeweler', '~> 1.4'
  require 'jeweler'

  Jeweler::Tasks.new do |gemspec|

    gemspec.version     = Merb::Slices::VERSION.dup

    gemspec.name        = "merb-slices"
    gemspec.description = "Merb plugin that supports reusable application 'slices'."
    gemspec.summary     = "Merb plugin for using and creating application 'slices' which help you modularize your application."

    gemspec.authors     = [ "Fabien Franzen" ]
    gemspec.email       = "info@fabien.be"
    gemspec.homepage    = "http://merbivore.com/"

    gemspec.files       = %w(Generators LICENSE Rakefile README TODO) + Dir['{bin,lib,spec}/**/*']

    # Runtime dependencies
    gemspec.add_dependency 'merb-core', "~> #{Merb::VERSION}"

    # Development dependencies
    gemspec.add_development_dependency 'rspec', '>= 1.2.9'

    # Executable files
    gemspec.executables = 'slice'

  end

  Jeweler::GemcutterTasks.new

rescue LoadError
  puts "Jeweler (or a dependency) not available. Install it with: gem install jeweler"
end

require 'spec/rake/spectask'
Spec::Rake::SpecTask.new(:spec) do |spec|
  spec.spec_opts << '--options' << 'spec/spec.opts' if File.exists?('spec/spec.opts')
  spec.libs << 'lib' << 'spec'
  spec.spec_files = FileList['spec/**/*_spec.rb']
end

Spec::Rake::SpecTask.new(:rcov) do |spec|
  spec.libs << 'lib' << 'spec'
  spec.pattern = 'spec/**/*_spec.rb'
  spec.rcov = true
end

task :default => :spec

require 'rake/rdoctask'
Rake::RDocTask.new do |rdoc|
  rdoc.rdoc_dir = 'rdoc'
  rdoc.title = "test_gem #{Merb::Slices::VERSION}"
  rdoc.rdoc_files.include('README*')
  rdoc.rdoc_files.include('lib/**/*.rb')
end
